name: electrical_store_mobile_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.9.1
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.14.4
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.4.2
  shared_preferences: ^2.5.3
  carousel_slider: ^5.1.1
  connectivity_plus: ^7.0.0
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.12
  firebase_core: ^3.3.0
  firebase_auth: ^5.3.0
  image_picker: ^1.0.4
  cloudinary_public: ^0.23.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/

